resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: cloudboss.jfrog.io/containers/teliaoss/github-pr-resource
    tag: v0.21.0

resources:
- name: version-snap
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudboss/cicd.git
    branch: master
    private_key: ((github-deploy-key-cicd))
    file: versions/keights/((git-branch))/snap
- name: keights-pr
  type: pull-request
  check_every: 12h
  webhook_token: ((github-keights-webhook-token))
  source:
    access_token: ((github-access-token))
    base_branch: ((git-branch))
    repository: cloudboss/keights
    required_review_approvals: 1
- name: keights-release
  type: git
  check_every: 12h
  webhook_token: ((github-keights-webhook-token))
  source:
    uri: git@github.com:cloudboss/keights.git
    private_key: ((github-deploy-key-keights))
    branch: ((git-branch))
    tag_filter: '((git-branch)).[[:digit:]]*-[[:digit:]]*'

jobs:
- name: build-pull-request
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      trigger: true
      version: every
    - get: version-snap
      params: { pre: snap }
  - put: keights-pr
    params:
      path: keights-pr
      status: pending
  - task: make-keights
    file: keights-pr/ci/tasks/make-keights.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
    params:
      REPO_SLUG: cloudboss/keights
      GITHUB_TOKEN: ((github-access-token))
      VERSION_FILE: version/version
  - task: build-ami
    file: keights-pr/ci/tasks/build-ami.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
    params:
      VERSION_FILE: version/version
  - put: version-snap
    params: { pre: snap }

- name: build-cluster-external-etcd
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      trigger: true
      version: every
      passed: [build-pull-request]
    - get: version-snap
      trigger: true
      passed: [build-pull-request]
  - task: build-cluster
    file: keights-pr/ci/tasks/build-cluster.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
    output_mapping:
      artifacts-out: build-cluster-artifacts
    params:
      CLUSTER: pipe-((git-branch))-ex-1
      KEIGHTS_BRANCH: ((git-branch))
      ETCD_MODE: external
  - task: run-e2e
    file: keights-pr/ci/tasks/run-e2e.yml
    input_mapping:
      artifacts-in: build-cluster-artifacts
      repo: keights-pr
    output_mapping:
      artifacts-out: run-e2e-artifacts
    ensure:
      task: s3-upload-results
      file: keights-pr/ci/tasks/s3-upload.yml
      input_mapping:
        version: version-snap
        artifacts-in: run-e2e-artifacts
      params:
        KEIGHTS_BRANCH: ((git-branch))
        JOB: build-cluster-external-etcd
  on_failure:
    put: keights-pr
    params:
      path: keights-pr
      status: failure
  ensure:
    try:
      task: delete-cluster
      file: keights-pr/ci/tasks/delete-cluster.yml
      attempts: 3
      input_mapping:
        repo: keights-pr
        version: version-snap
      params:
        CLUSTER: pipe-((git-branch))-ex-1
        KEIGHTS_BRANCH: ((git-branch))
        ETCD_MODE: external

- name: upgrade-cluster-external-etcd
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      trigger: true
      version: every
      passed: [build-pull-request]
    - get: version-snap
      trigger: true
      passed: [build-pull-request]
  - task: build-initial-cluster
    file: keights-pr/ci/tasks/build-cluster.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
    output_mapping:
      artifacts-out: initial-cluster-artifacts
    params:
      START_UPGRADE: troo
      CLUSTER: pipe-((git-branch))-ex-2
      KEIGHTS_BRANCH: ((git-branch))
      ETCD_MODE: external
  - task: upgrade-cluster
    file: keights-pr/ci/tasks/build-cluster.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
      artifacts-in: initial-cluster-artifacts
    output_mapping:
      artifacts-out: upgraded-cluster-artifacts
    params:
      CLUSTER: pipe-((git-branch))-ex-2
      KEIGHTS_BRANCH: ((git-branch))
      ETCD_MODE: external
  - task: run-e2e
    file: keights-pr/ci/tasks/run-e2e.yml
    input_mapping:
      artifacts-in: upgraded-cluster-artifacts
      repo: keights-pr
    output_mapping:
      artifacts-out: run-e2e-artifacts
    ensure:
      task: s3-upload-results
      file: keights-pr/ci/tasks/s3-upload.yml
      input_mapping:
        version: version-snap
        artifacts-in: run-e2e-artifacts
      params:
        KEIGHTS_BRANCH: ((git-branch))
        JOB: upgrade-cluster-external-etcd
  on_failure:
    put: keights-pr
    params:
      path: keights-pr
      status: failure
  ensure:
    try:
      task: delete-cluster
      file: keights-pr/ci/tasks/delete-cluster.yml
      attempts: 3
      input_mapping:
        repo: keights-pr
        version: version-snap
      params:
        CLUSTER: pipe-((git-branch))-ex-2
        KEIGHTS_BRANCH: ((git-branch))
        ETCD_MODE: external

- name: build-cluster-stacked-etcd
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      trigger: true
      version: every
      passed: [build-pull-request]
    - get: version-snap
      trigger: true
      passed: [build-pull-request]
  - task: build-cluster
    file: keights-pr/ci/tasks/build-cluster.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
    output_mapping:
      artifacts-out: build-cluster-artifacts
    params:
      CLUSTER: pipe-((git-branch))-st-1
      KEIGHTS_BRANCH: ((git-branch))
      ETCD_MODE: stacked
  - task: run-e2e
    file: keights-pr/ci/tasks/run-e2e.yml
    input_mapping:
      artifacts-in: build-cluster-artifacts
      repo: keights-pr
    output_mapping:
      artifacts-out: run-e2e-artifacts
    ensure:
      task: s3-upload-results
      file: keights-pr/ci/tasks/s3-upload.yml
      input_mapping:
        version: version-snap
        artifacts-in: run-e2e-artifacts
      params:
        KEIGHTS_BRANCH: ((git-branch))
        JOB: build-cluster-stacked-etcd
  on_failure:
    put: keights-pr
    params:
      path: keights-pr
      status: failure
  ensure:
    try:
      task: delete-cluster
      file: keights-pr/ci/tasks/delete-cluster.yml
      attempts: 3
      input_mapping:
        repo: keights-pr
        version: version-snap
      params:
        CLUSTER: pipe-((git-branch))-st-1
        KEIGHTS_BRANCH: ((git-branch))
        ETCD_MODE: stacked

- name: upgrade-cluster-stacked-etcd
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      trigger: true
      version: every
      passed: [build-pull-request]
    - get: version-snap
      trigger: true
      passed: [build-pull-request]
  - task: build-initial-cluster
    file: keights-pr/ci/tasks/build-cluster.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
    output_mapping:
      artifacts-out: initial-cluster-artifacts
    params:
      START_UPGRADE: troo
      CLUSTER: pipe-((git-branch))-st-2
      KEIGHTS_BRANCH: ((git-branch))
      ETCD_MODE: stacked
  - task: upgrade-cluster
    file: keights-pr/ci/tasks/build-cluster.yml
    input_mapping:
      repo: keights-pr
      version: version-snap
      artifacts-in: initial-cluster-artifacts
    output_mapping:
      artifacts-out: upgraded-cluster-artifacts
    params:
      CLUSTER: pipe-((git-branch))-st-2
      KEIGHTS_BRANCH: ((git-branch))
      ETCD_MODE: stacked
  - task: run-e2e
    file: keights-pr/ci/tasks/run-e2e.yml
    input_mapping:
      artifacts-in: upgraded-cluster-artifacts
      repo: keights-pr
    output_mapping:
      artifacts-out: run-e2e-artifacts
    ensure:
      task: s3-upload-results
      file: keights-pr/ci/tasks/s3-upload.yml
      input_mapping:
        version: version-snap
        artifacts-in: run-e2e-artifacts
      params:
        KEIGHTS_BRANCH: ((git-branch))
        JOB: upgrade-cluster-stacked-etcd
  on_failure:
    put: keights-pr
    params:
      path: keights-pr
      status: failure
  ensure:
    try:
      task: delete-cluster
      file: keights-pr/ci/tasks/delete-cluster.yml
      attempts: 3
      input_mapping:
        repo: keights-pr
        version: version-snap
      params:
        CLUSTER: pipe-((git-branch))-st-2
        KEIGHTS_BRANCH: ((git-branch))
        ETCD_MODE: stacked

- name: update-pull-request-status
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      trigger: true
      version: every
      passed:
      - build-cluster-external-etcd
      - upgrade-cluster-external-etcd
      - build-cluster-stacked-etcd
      - upgrade-cluster-stacked-etcd
    - get: version-snap
      trigger: true
      passed:
      - build-cluster-external-etcd
      - upgrade-cluster-external-etcd
      - build-cluster-stacked-etcd
      - upgrade-cluster-stacked-etcd
  - put: keights-pr
    params:
      path: keights-pr
      status: success

- name: build-release
  public: true
  plan:
  - in_parallel:
    - get: keights-pr
      passed: [update-pull-request-status]
    - get: keights-release
      trigger: true
    - get: version-snap
      passed: [update-pull-request-status]
  - task: verify-release
    file: keights-release/ci/tasks/verify-release.yml
    input_mapping:
      repo-release: keights-release
      repo-pr: keights-pr
      version: version-snap
  - task: make-keights
    file: keights-release/ci/tasks/make-keights.yml
    input_mapping:
      repo: keights-release
    params:
      REPO_SLUG: cloudboss/keights
      GITHUB_TOKEN: ((github-access-token))
      VERSION_FILE: repo/.git/ref
  - task: build-ami
    file: keights-release/ci/tasks/build-ami.yml
    input_mapping:
      repo: keights-release
    params:
      VERSION_FILE: repo/.git/ref
