AWSTemplateFormatVersion: '2010-09-09'

Description: Kubernetes master resources

Parameters:
  ClusterName:
    Description: Name of Kubernetes cluster
    Type: String
  NumInstances:
    Description: Number of master instances
    Type: Number
    Default: 1
    AllowedValues: [1, 3]
    ConstraintDescription: You must choose an odd number of instances
  VpcId:
    Description: ID of VPC where cluster will be placed
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Description: >-
      List of subnets IDs in VPC where cluster will be placed.
      The number of subnets must match the NumInstances parameter.
    Type: List<AWS::EC2::Subnet::Id>
  LoadBalancerSubnetIds:
    Description: >-
      List of subnets IDs in VPC for API load balancer.
      The number of subnets must match the NumInstances parameter.
    Type: List<AWS::EC2::Subnet::Id>
  ImageId:
    Description: ID of AMI used for instances
    Type: AWS::EC2::Image::Id
    Default: ami-0ea27a3490f9dfe8a
  InstanceType:
    Description: Type of EC2 instance
    Type: String
  KeyPair:
    Description: SSH keypair assigned to instances
    Type: AWS::EC2::KeyPair::KeyName
  IamInstanceProfile:
    Description: Name of IAM Instance profile to assign to instances
    Type: String
  LoadBalancerScheme:
    Description: Scheme of API load balancer
    Type: String
    Default: internal
    AllowedValues:
      - internal
      - internet-facing
  ApiServerSecurityGroup:
    Description: Security group for kube-apiserver
    Type: String
  KubeletSecurityGroup:
    Description: Security group for kubelet
    Type: String
  LambdaRoleArn:
    Description: Role ARN to assign to helper Lamba functions
    Type: String
  KmsKeyId:
    Description: KMS key used to manage secrets
    Type: String
    Default: ''
  PodCidr:
    Description: CIDR block of addresses for pods
    Default: 10.0.0.0/16
    Type: String
  ServiceCidr:
    Description: CIDR block of addresses for services
    Default: 10.1.0.0/16
    Type: String
  SshAccessCidr:
    Description: CIDR block given ssh access to cluster
    Default: 0.0.0.0/0
    Type: String
  ApiAccessCidr:
    Description: CIDR block given API access to cluster
    Default: 0.0.0.0/0
    Type: String
  ClusterDns:
    Description: >-
      IP addres of cluster DNS server; should be
      the value of ServiceCidr + 10
    Default: 10.1.0.10
    Type: String
  EtcdVolumeSize:
    Description: Size of etcd volume in GB
    Default: 10
    Type: Number
  HyperkubeImage:
    Description: Docker image containing kube-apiserver
    Type: String
    Default: gcr.io/google_containers/hyperkube-amd64:v1.9.4
  EtcdImage:
    Description: Docker image containing etcd
    Type: String
    Default: gcr.io/google_containers/etcd-amd64:3.0.17
  KubernetesVersion:
    Description: Version of Kubernetes
    Type: String
    Default: 1.9.4

Mappings:
  LambdaUrls:
    AllFunctions:
      Bucket: cloudboss-public
    SubnetToAzFunction:
      Key: lambda/co/cloudboss/stackhand/subnet_to_az/0.1.0/go1.x/subnet_to_az-0.1.0.zip
    KubeCaFunction:
      Key: lambda/co/cloudboss/stackhand/kube_ca/0.1.0/go1.x/kube_ca-0.1.0.zip

Conditions:
  HasThreeMasters: !Equals [!Ref NumInstances, 3]

Resources:
  SubnetToAzFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !FindInMap [LambdaUrls, AllFunctions, Bucket]
        S3Key: !FindInMap [LambdaUrls, SubnetToAzFunction, Key]
      Handler: subnet_to_az
      Runtime: go1.x
      Timeout: 30
      Role: !Ref LambdaRoleArn

  KubeCaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !FindInMap [LambdaUrls, AllFunctions, Bucket]
        S3Key: !FindInMap [LambdaUrls, KubeCaFunction, Key]
      Handler: kube_ca
      Runtime: go1.x
      MemorySize: 512
      Timeout: 30
      Role: !Ref LambdaRoleArn

  SubnetToAz1:
    Type: Custom::SubnetToAz
    DependsOn: SubnetToAzFunction
    Properties:
      ServiceToken: !GetAtt [SubnetToAzFunction, Arn]
      SubnetId: !Select [0, !Ref SubnetIds]

  SubnetToAz2:
    Type: Custom::SubnetToAz
    DependsOn: SubnetToAzFunction
    Condition: HasThreeMasters
    Properties:
      ServiceToken: !GetAtt [SubnetToAzFunction, Arn]
      SubnetId: !Select [1, !Ref SubnetIds]

  SubnetToAz3:
    Type: Custom::SubnetToAz
    DependsOn: SubnetToAzFunction
    Condition: HasThreeMasters
    Properties:
      ServiceToken: !GetAtt [SubnetToAzFunction, Arn]
      SubnetId: !Select [2, !Ref SubnetIds]

  KubeCa:
    Type: Custom::KubeCa
    DependsOn: KubeCaFunction
    Properties:
      ServiceToken: !GetAtt [KubeCaFunction, Arn]
      ClusterName: !Ref ClusterName
      ServiceCidr: !Ref ServiceCidr
      LoadBalancerName: !GetAtt [LoadBalancer, DNSName]
      NumInstances: !Ref NumInstances
      KmsKeyId: !Ref KmsKeyId

  EtcdSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for etcd
      VpcId: !Ref VpcId

  EtcdSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EtcdSecurityGroup
      SourceSecurityGroupId: !Ref EtcdSecurityGroup
      FromPort: 2379
      ToPort: 2380
      IpProtocol: tcp

  EtcdSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EtcdSecurityGroup
      DestinationSecurityGroupId: !Ref EtcdSecurityGroup
      FromPort: 2379
      ToPort: 2380
      IpProtocol: tcp

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ClusterName} load balancer
      VpcId: !Ref VpcId

  LoadBalancerSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EtcdSecurityGroup
      SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      FromPort: 2379
      ToPort: 2380
      IpProtocol: tcp

  LoadBalancerSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref LoadBalancerSecurityGroup
      CidrIp: !Ref ApiAccessCidr
      FromPort: 443
      IpProtocol: tcp
      ToPort: 443

  LoadBalancerSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref LoadBalancerSecurityGroup
      DestinationSecurityGroupId: !Ref AutoscalingGroupSecurityGroup
      FromPort: 6443
      ToPort: 6443
      IpProtocol: tcp

  LoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      CrossZone: true
      HealthCheck:
        HealthyThreshold: 3
        Interval: 30
        Target: TCP:6443
        Timeout: 10
        UnhealthyThreshold: 3
      LoadBalancerName: !Ref ClusterName
      Listeners:
        - InstancePort: 6443
          InstanceProtocol: TCP
          Protocol: TCP
          LoadBalancerPort: 443
      Scheme: !Ref LoadBalancerScheme
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Ref LoadBalancerSubnetIds

  AutoscalingGroupSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for autoscaling group
      VpcId: !Ref VpcId

  AutoscalingGroupIngressSsh:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AutoscalingGroupSecurityGroup
      CidrIp: !Ref SshAccessCidr
      FromPort: 22
      IpProtocol: tcp
      ToPort: 22

  AutoscalingGroupIngressLoadBalancer:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AutoscalingGroupSecurityGroup
      SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      FromPort: 6443
      IpProtocol: tcp
      ToPort: 6443

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: KubeCa
    Properties:
      DesiredCapacity: !Ref NumInstances
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: !Ref NumInstances
      MinSize: !Ref NumInstances
      VPCZoneIdentifier: !Ref SubnetIds
      LoadBalancerNames: [!Ref LoadBalancer]
      Tags:
        - Key: Name
          Value: !Sub ${ClusterName}-master
          PropagateAtLaunch: true
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        SuspendProcesses:
          - HealthCheck

  Volume1:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt [SubnetToAz1, AvailabilityZone]
      Size: !Ref EtcdVolumeSize
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: !Ref AutoScalingGroup
        - Key: etcd:instance
          Value: 1

  Volume2:
    Type: AWS::EC2::Volume
    Condition: HasThreeMasters
    Properties:
      AvailabilityZone: !GetAtt [SubnetToAz2, AvailabilityZone]
      Size: !Ref EtcdVolumeSize
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: !Ref AutoScalingGroup
        - Key: etcd:instance
          Value: 2

  Volume3:
    Type: AWS::EC2::Volume
    Condition: HasThreeMasters
    Properties:
      AvailabilityZone: !GetAtt [SubnetToAz3, AvailabilityZone]
      Size: !Ref EtcdVolumeSize
      VolumeType: gp2
      Tags:
        - Key: Name
          Value: !Ref AutoScalingGroup
        - Key: etcd:instance
          Value: 3

  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      PlacementTenancy: default
      SecurityGroups:
        - !Ref ApiServerSecurityGroup
        - !Ref KubeletSecurityGroup
        - !Ref AutoscalingGroupSecurityGroup
        - !Ref EtcdSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #cloud-config
            write_files:
              - path: /etc/systemd/system/keights-collector.service.d/environment.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=AWS_REGION=${AWS::Region}
                  Environment=KEIGHTS_VOLUME_TAG=etcd:instance

              - path: /etc/systemd/system/keights-share.service.d/environment.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=KEIGHTS_DOMAIN=k8s.local
                  Environment=KEIGHTS_PREFIX=${ClusterName}

              - path: /etc/systemd/system/keights-templatize-etcd.service.d/environment.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=AWS_REGION=${AWS::Region}
                  Environment=KEIGHTS_DOMAIN=k8s.local
                  Environment=KEIGHTS_ETCD_CLUSTER_TOKEN=etcd-${ClusterName}
                  Environment=KEIGHTS_ETCD_IMAGE=${EtcdImage}
                  Environment=KEIGHTS_PREFIX=${ClusterName}

              - path: /etc/systemd/system/keights-volumize.service.d/environment.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=AWS_REGION=${AWS::Region}
                  Environment=KEIGHTS_VOLUME_TAG=etcd:instance
                  Environment=KEIGHTS_VOLUME_DEVICE=xvdg

              - path: /etc/systemd/system/var-lib-etcd.mount.d/mount.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Mount]
                  What=/dev/xvdg

              - path: /etc/systemd/system/keights-whisper-controller.service.d/environment.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=AWS_REGION=${AWS::Region}
                  Environment=KEIGHTS_CLUSTER_NAME=${ClusterName}

              - path: /etc/systemd/system/keights-templatize-kubeadm-config.service.d/environment.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=AWS_REGION=${AWS::Region}
                  Environment=KEIGHTS_DOMAIN=k8s.local
                  Environment=KEIGHTS_PREFIX=${ClusterName}
                  Environment=KEIGHTS_APISERVER=${LoadBalancer.DNSName}
                  Environment=KEIGHTS_POD_SUBNET=${PodCidr}
                  Environment=KEIGHTS_SERVICE_SUBNET=${ServiceCidr}
                  Environment=KEIGHTS_HYPERKUBE_IMAGE=${HyperkubeImage}
                  Environment=KEIGHTS_KUBERNETES_VERSION=v${KubernetesVersion}

              - path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
                owner: root:root
                permissions: '0644'
                content: |
                  [Service]
                  Environment=KEIGHTS_CLUSTER_DOMAIN=k8s.local
                  ExecStart=
                  ExecStart=/usr/bin/kubelet \
                              --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf \
                              --kubeconfig=/etc/kubernetes/kubelet.conf \
                              --pod-manifest-path=/etc/kubernetes/manifests \
                              --allow-privileged=true \
                              --network-plugin=cni \
                              --cni-conf-dir=/etc/cni/net.d \
                              --cni-bin-dir=/opt/cni/bin \
                              --cluster-dns=${ClusterDns} \
                              --cluster-domain=${!KEIGHTS_CLUSTER_DOMAIN} \
                              --authorization-mode=Webhook \
                              --client-ca-file=/etc/kubernetes/pki/ca.crt \
                              --cadvisor-port=0 \
                              --rotate-certificates=true \
                              --cert-dir=/var/lib/kubelet/pki \
                              --cloud-provider=aws

            runcmd:
              - systemctl daemon-reload
              - systemctl enable var-lib-etcd.mount
              - systemctl enable kubelet.service
              - systemctl enable keights-collector.timer
              - systemctl enable keights-share.path
              - systemctl enable keights-templatize-etcd.service
              - systemctl enable keights-templatize-kubeadm-config.service
              - systemctl enable keights-whisper-controller.service
              - systemctl start --no-block kubelet.service
              - systemctl start --no-block keights-add-addon.service
              - systemctl start --no-block keights-collector.timer
              - systemctl start --no-block keights-share.path
              - systemctl start --no-block keights-kubeadm-init.service

Outputs:
  LoadBalancerDnsName:
    Description: DNS name of load balancer
    Value: !GetAtt [LoadBalancer, DNSName]
  AutoscalingGroupSecurityGroup:
    Description: Security group of autoscaling group
    Value: !Ref AutoscalingGroupSecurityGroup
  EtcdSecurityGroup:
    Description: Security group for etcd
    Value: !Ref EtcdSecurityGroup
  LoadBalancerSecurityGroup:
    Description: Security group of load balancer
    Value: !Ref LoadBalancerSecurityGroup
  AutoScalingGroup:
    Description: Name of autoscaling group
    Value: !Ref AutoScalingGroup
