apiVersion: v1
kind: Pod
metadata:
  name: kube-addon-manager
  namespace: kube-system
  labels:
    component: kube-addon-manager
spec:
  hostNetwork: true
  containers:
  - name: kube-addon-manager
    image: gcr.io/google_containers/kube-addon-manager:v8.6
    command:
    - /opt/kube-addons.sh
    env:
    - name: KUBECONFIG
      value: /etc/kubernetes/admin.conf
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
    volumeMounts:
    - name: addons
      mountPath: /etc/kubernetes
      readOnly: true
  volumes:
  - name: addons
    hostPath:
      path: /etc/kubernetes
