builds:
  - binary: keights
    goos:
      - linux
    goarch:
      - amd64
fpm:
  vendor: Cloudboss Corporation
  homepage: https://github.com/cloudboss/keights
  maintainer: Joseph Wright <joseph@cloudboss.co>
  description: Utilities for boostrapping Kubernetes
  license: MIT
  formats:
    - deb
  bindir: /usr/bin
  files:
    fpm/etc/kubernetes/addons/kubernetes-dashboard.yaml:
      /etc/kubernetes/addons/kubernetes-dashboard.yaml
    fpm/etc/kubernetes/addons/kube-router.yaml:
      /etc/kubernetes/addons/kube-router.yaml
    fpm/etc/kubernetes/addons/storage.yaml:
      /etc/kubernetes/addons/storage.yaml
    fpm/usr/lib/tmpfiles.d/keights.conf:
      /usr/lib/tmpfiles.d/keights.conf
    fpm/usr/lib/systemd/system/keights-add-addon.service:
      /usr/lib/systemd/system/keights-add-addon.service
    fpm/usr/lib/systemd/system/keights-collector.service:
      /usr/lib/systemd/system/keights-collector.service
    fpm/usr/lib/systemd/system/keights-collector.timer:
      /usr/lib/systemd/system/keights-collector.timer
    fpm/usr/lib/systemd/system/keights-kubeadm-init.service:
      /usr/lib/systemd/system/keights-kubeadm-init.service
    fpm/usr/lib/systemd/system/keights-kubeadm-join.service:
      /usr/lib/systemd/system/keights-kubeadm-join.service
    fpm/usr/lib/systemd/system/keights-templates.target:
      /usr/lib/systemd/system/keights-templates.target
    fpm/usr/lib/systemd/system/keights-share.path:
      /usr/lib/systemd/system/keights-share.path
    fpm/usr/lib/systemd/system/keights-share.service:
      /usr/lib/systemd/system/keights-share.service
    fpm/usr/lib/systemd/system/keights-templatize-etcd.service:
      /usr/lib/systemd/system/keights-templatize-etcd.service
    fpm/usr/lib/systemd/system/keights-templatize-kubeadm-config.service:
      /usr/lib/systemd/system/keights-templatize-kubeadm-config.service
    fpm/usr/lib/systemd/system/keights-volumize.service:
      /usr/lib/systemd/system/keights-volumize.service
    fpm/usr/lib/systemd/system/keights-whisper-controller.service:
      /usr/lib/systemd/system/keights-whisper-controller.service
    fpm/usr/lib/systemd/system/keights-whisper-node.service:
      /usr/lib/systemd/system/keights-whisper-node.service
    fpm/usr/lib/systemd/system/var-lib-etcd.mount:
      /usr/lib/systemd/system/var-lib-etcd.mount
    fpm/usr/share/keights/kube-addon-manager.yaml:
      /usr/share/keights/kube-addon-manager.yaml
    fpm/usr/share/keights/etcd.yaml.template:
      /usr/share/keights/etcd.yaml.template
    fpm/usr/share/keights/kubeadm-config.yaml.template:
      /usr/share/keights/kubeadm-config.yaml.template
