---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: '3.6'

inputs:
- name: repo
- name: version
  optional: true

caches:
- path: ../../../python
- path: ../../../opt/bin

params:
  AWS_REGION: us-east-1
  VPC_ID: vpc-c71371be
  SUBNET_ID: subnet-37ef771b
  PACKER_URL: https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip
  VERSION_FILE: version/version

run:
  path: /bin/sh
  args:
  - -e
  - -c
  - |
    if [ ! -x /opt/bin/packer ]; then
        apt-get update && apt-get install --no-install-recommends unzip
        curl -o /tmp/packer.zip ${PACKER_URL}
        unzip -d /opt/bin /tmp/packer.zip
    fi

    python3 -m venv /python
    /python/bin/pip install -r repo/stack/ami/requirements.txt
    . /python/bin/activate

    version=`cat ${VERSION_FILE}`
    first_char=`echo ${version} | cut -c 1`
    [ "${first_char=}" != v ] && version="v${version}"

    k8s_version=`echo ${version} | cut -d - -f 1 | cut -c 2-100`

    cd repo/stack/ami/debian
    /opt/bin/packer build \
        -var keights-version=${version} \
        -var k8s-version=${k8s_version} \
        -var vpc-id=${VPC_ID} \
        -var subnet-id=${SUBNET_ID} \
        build.json
