---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudboss/docker.io/library/golang
    tag: '1.17.8'

inputs:
- name: repo
- name: version
  optional: true

caches:
- path: ../../../root/go

params:
  REPO_SLUG: cloudboss/keights
  VERSION_FILE: version/version
  GITHUB_TOKEN:

run:
  path: /bin/sh
  args:
  - -e
  - -c
  - |
    unset GOPATH

    version=`cat ${VERSION_FILE}`
    first_char=`echo ${version} | cut -c 1`
    [ "${first_char=}" != v ] && version="v${version}"

    apt-get update
    apt-get install -y --no-install-recommends jq rpm zip

    cd repo
    make test
    make github-release VERSION=${version} REPO_SLUG=${REPO_SLUG}
