---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: '3.7.2-alpine'

inputs:
- name: version
- name: artifacts-in

caches:
- path: ../../../python

params:
  BUCKET: cloudboss-public
  KEIGHTS_BRANCH:
  JOB:

run:
  path: /bin/sh
  args:
  - -e
  - -c
  - |
    python3 -m venv /python
    . /python/bin/activate
    pip install awscli

    obj_path=artifacts-in/*.tar.gz

    if [ ! -f ${obj_path} ]; then
        echo "No results to upload"
        exit 0
    fi

    obj=`basename ${obj_path}`
    version=`cat version/version`
    dest=`echo s3://${BUCKET}/ci/keights-${KEIGHTS_BRANCH}/${JOB}/${version}/sonobuoy-out/${obj}`
    echo "Sonobuoy results are being uploaded to ${dest}"
    aws s3 cp ${obj_path} ${dest}
