cluster_name: '{{ cluster }}'
vpc_id: vpc-ba92ad08
subnet_ids: subnet-6c31888d,subnet-f3cdd152,subnet-e245724f
extra_master_security_groups: [sg-d55a9acdd085d603c, sg-dd75b80d331429d54]
resource_bucket: cloudboss-public
num_masters: 3
image_id: ami-05d0a1d4548c65003
master_instance_type: m4.large
keypair: keights
load_balancer_scheme: internet-facing
kms_key_id: d4baff42-9ea6-4f7d-a866-136587c77815
kms_key_alias: alias/cloudboss
k8s_version: 1.10.0
etcd_image: k8s.gcr.io/etcd-amd64:3.1.12
pod_cidr: 10.0.0.0/16
service_cidr: 10.1.0.0/16
ssh_access_cidr: 0.0.0.0/0
api_access_cidr: 0.0.0.0/0
etcd_volume_size: 10
node_groups:
  - name: standard
    num_nodes: 3
    vpc_id: '{{ vpc_id }}'
    subnet_ids: '{{ subnet_ids }}'
    image_id: '{{ image_id }}'
    instance_type: m3.medium
    keypair: '{{ keypair }}'
    ssh_access_cidr: '{{ ssh_access_cidr }}'
    node_labels: size=standard,env=dev
    extra_security_groups: [sg-ba2b334299d1e9a9e]
