cluster_name: '{{ env }}'
vpc_id: vpc-ba92ad08
subnet_ids: subnet-6c31888d,subnet-f3cdd152,subnet-e245724f
num_masters: 3
num_nodes: 3
node_labels: 'size=standard,env=dev'
image_id: ami-03d0b653e1a63db94
instance_type: m4.large
keypair: keights
load_balancer_scheme: internet-facing
kms_key_id: d4baff42-9ea6-4f7d-a866-136587c77815
kms_key_alias: alias/cloudboss
k8s_version: 1.9.6
kube_router_version: 0.1.0
etcd_version: 3.0.17
pod_cidr: 10.0.0.0/16
service_cidr: 10.1.0.0/16
ssh_access_cidr: 0.0.0.0/0
api_access_cidr: 0.0.0.0/0
etcd_volume_size: 1
