---
- name: set default values
  set_fact:
    cluster_dns: '{{ keights_stack.masters.service_cidr.split(".")[:-1] | join(".") }}.10'
    k8s_version: '{{ keights_stack.k8s_version | default(keights_version.split("-")[0]) }}'
    default_image: 'debian-buster-k8s-hvm-amd64-{{ keights_version }}'
    cache_dir: '{{ playbook_dir }}/.cache'
    create_iam_resources: '{{ keights_stack.create_iam_resources | default(true) }}'
    default_docker_options:
      'ip-masq': false
      'iptables': false
      'log-driver': journald
      'storage-driver': overlay2

- name: set etcd device
  set_fact:
    etcd_device: '{{ keights_stack.etcd.device | default("/dev/xvdg") }}'
  when: 'etcd_mode == "external"'

- name: set etcd device
  set_fact:
    etcd_device: '{{ keights_stack.masters.etcd_device | default("/dev/xvdg") }}'
  when: 'etcd_mode == "stacked"'

- name: ensure cache directory
  file:
    path: '{{ cache_dir }}'
    state: directory

- name: find ami
  ec2_ami_info:
    owners: '{{ keights_stack.image_owner | default("256008164056") }}'
    filters:
      name: '{{ keights_stack.image | default(default_image) }}'
  register: ami
  when: keights_stack.lookup_image | default(lookup_image)

- name: assert that at least one ami is found
  assert:
    that: ami.images | length > 0
    msg: 'expected to find at least one ami with name {{ keights_stack.image | default(default_image) }}'
  when: keights_stack.lookup_image | default(lookup_image)

- name: assert valid value for etcd_mode
  assert:
    that: etcd_mode in ('stacked', 'external')
    msg: "keights_stack.etcd_mode must be one of 'stacked' or 'external'"

- name: assert the correct number of master subnet ids
  assert:
    that: keights_stack.masters.subnet_ids | length in (1, 3)
    msg: 'expected to be given 1 or 3 master subnet ids, got {{ keights_stack.masters.subnet_ids | length }}'

- name: assert valid value for create_iam_resources
  assert:
    that: create_iam_resources in (true, false)
    msg: keights_stack.create_iam_resources must be a boolean true or false value

- name: assert that kms key id is defined when creating iam resources
  assert:
    that: keights_stack.kms_key_id is defined
  when: create_iam_resources

- name: assert that iam role arns are defined for lambdas
  assert:
    that:
    - keights_stack.instattr_lambda_role_arn is defined
    - keights_stack.auto_namer_lambda_role_arn is defined
    - keights_stack.kube_ca_lambda_role_arn is defined
    - keights_stack.subnet_to_az_lambda_role_arn is defined
    - keights_stack.basic_lambda_role_arn is defined
    msg: iam role arns for lambdas must be defined when create_iam_resources is false
  when: not create_iam_resources

- name: assert that instance profiles are defined for masters
  assert:
    that: keights_stack.masters.instance_profile is defined
    msg: keights_stack.masters.instance_profile must be defined when create_iam_resources is false
  when: not create_iam_resources

- name: assert that instance profiles are defined for etcd
  assert:
    that: keights_stack.etcd.instance_profile is defined
    msg: keights_stack.etcd.instance_profile must be defined when create_iam_resources is false
  when: 'not create_iam_resources and etcd_mode == "external"'

- name: assert that instance profiles are defined for nodes
  assert:
    that: (keights_stack.node_groups | map(attribute='instance_profile') | list | length) == (keights_stack.node_groups | length)
    msg: instance_profile must be defined for each node group when create_iam_resources is false
  when: not create_iam_resources

- name: set image id
  set_fact:
    image_id: '{{ ami.images[0].image_id }}'
  when: keights_stack.lookup_image | default(lookup_image)

- name: find lambda archives in s3
  aws_s3:
    bucket: '{{ keights_stack.resource_bucket }}'
    object: 'stackbot/{{ item }}/{{ keights_version }}/go1.x/{{ item }}-{{ keights_version }}.zip'
    mode: geturl
  register: stackbots
  loop:
    - auto_namer
    - instattr
    - kube_ca
    - subnet_to_az
  changed_when: false
  failed_when: false
  tags:
    - lambda

- name: download lambda archives releases
  get_url:
    url: https://github.com/cloudboss/keights/releases/download/{{ keights_version }}/{{ item.item }}-{{ keights_version }}.zip
    dest: '{{ cache_dir }}'
  loop: '{{ stackbots.results }}'
  when: '"url" not in item'
  tags:
    - lambda

- name: upload lambda archives to s3
  aws_s3:
    bucket: '{{ keights_stack.resource_bucket }}'
    object: 'stackbot/{{ item.item }}/{{ keights_version }}/go1.x/{{ item.item }}-{{ keights_version }}.zip'
    mode: put
    src: '{{ cache_dir }}/{{ item.item }}-{{ keights_version }}.zip'
  loop: '{{ stackbots.results }}'
  when: '"url" not in item'
  tags:
    - lambda

- name: build common stack
  cloudformation:
    stack_name: '{{ keights_stack.cluster_name }}-common'
    role_arn: '{{ keights_stack.cfn_role_arn | default(omit) }}'
    template: '{{ role_path }}/files/common.yml'
    template_parameters:
      VpcId: '{{ keights_stack.vpc_id }}'
      ClusterName: '{{ keights_stack.cluster_name }}'
      CreateIamResources: '{{ create_iam_resources | lower }}'
      InstAttrLambdaRoleArn: '{{ keights_stack.instattr_lambda_role_arn | default("") }}'
      EtcdMode: '{{ etcd_mode }}'
      EtcdDomain: '{{ keights_stack.etcd_domain | default(default_etcd_domain) }}'
      EtcdHostedZoneId: '{{ keights_stack.etcd_hosted_zone_id | default("") }}'
      KmsKeyId: '{{ keights_stack.kms_key_id | default("") }}'
      ApiAccessCidr: '{{ keights_stack.api_access_cidr }}'
      # TODO: give masters and nodes separate ssh_access_cidr
      SshAccessCidr: '{{ keights_stack.ssh_access_cidr }}'
      NodePortAccessCidr: '{{ keights_stack.node_port_access_cidr | default("") }}'
      KeightsVersion: '{{ keights_version }}'
      ResourceBucket: '{{ keights_stack.resource_bucket }}'
    tags:
      KubernetesCluster: '{{ keights_stack.cluster_name }}'
      k8s:version: '{{ k8s_version }}'
      keights:version: '{{ keights_version }}'
  register: common_stack
  tags:
    - common

- name: set iam variables
  set_fact:
    master_instance_profile: '{{ common_stack.stack_outputs.MasterInstanceProfile | default(keights_stack.masters.instance_profile) }}'
    auto_namer_lambda_role_arn: '{{ common_stack.stack_outputs.AutoNamerLambdaRoleArn | default(keights_stack.auto_namer_lambda_role_arn) }}'
    kube_ca_lambda_role_arn: '{{ common_stack.stack_outputs.KubeCaLambdaRoleArn | default(keights_stack.kube_ca_lambda_role_arn) }}'
    subnet_to_az_lambda_role_arn: '{{ common_stack.stack_outputs.SubnetToAzLambdaRoleArn | default(keights_stack.subnet_to_az_lambda_role_arn) }}'
    basic_lambda_role_arn: '{{ common_stack.stack_outputs.BasicLambdaRoleArn | default(keights_stack.basic_lambda_role_arn) }}'

- name: set etcd iam instance profile
  set_fact:
    etcd_instance_profile: '{{ common_stack.stack_outputs.EtcdInstanceProfile | default(keights_stack.etcd.instance_profile) }}'
  when: 'etcd_mode == "external"'

- name: build etcd stack
  cloudformation:
    stack_name: '{{ keights_stack.cluster_name }}-etcd'
    role_arn: '{{ keights_stack.cfn_role_arn | default(omit) }}'
    template: '{{ role_path }}/files/etcd.yml'
    template_parameters:
      ClusterName: '{{ keights_stack.cluster_name }}'
      NumInstances: '{{ keights_stack.etcd.subnet_ids | length }}'
      VpcId: '{{ keights_stack.vpc_id }}'
      SubnetIds: '{{ keights_stack.etcd.subnet_ids | join(",") }}'
      ImageId: '{{ keights_stack.etcd.image_id if keights_stack.etcd.image_id is defined else image_id }}'
      InstanceType: '{{ keights_stack.etcd.instance_type }}'
      KeyPair: '{{ keights_stack.etcd.keypair }}'
      InstanceProfile: '{{ etcd_instance_profile }}'
      SecurityGroups: '{{ ([common_stack.stack_outputs.EtcdSecurityGroup] + keights_stack.etcd.extra_security_groups | default([])) | join(",") }}'
      AutoNamerLambdaRoleArn: '{{ auto_namer_lambda_role_arn }}'
      KubeCaLambdaRoleArn: '{{ kube_ca_lambda_role_arn }}'
      SubnetToAzLambdaRoleArn: '{{ subnet_to_az_lambda_role_arn }}'
      KmsKeyId: '{{ keights_stack.kms_key_alias }}'
      HostedZoneId: '{{ common_stack.stack_outputs.HostedZoneId | default(keights_stack.etcd_hosted_zone_id) }}'
      Domain: '{{ keights_stack.etcd_domain | default(default_etcd_domain) }}'
      Prefix: '{{ keights_stack.etcd_prefix | default("etcd") }}'
      VolumeSize: '{{ keights_stack.etcd.volume_size | default(10) }}'
      Device: '{{ etcd_device if etcd_device.startswith("/dev/") else "/dev/{}".format(etcd_device) }}'
      EtcdVersion: '{{ keights_stack.etcd.etcd_version | default(default_etcd_version) }}'
      ImageRepository: '{{ keights_stack.etcd.image_repository | default("k8s.gcr.io") }}'
      KeightsVersion: '{{ keights_version }}'
      ResourceBucket: '{{ keights_stack.resource_bucket }}'
      # Piping to_json twice escapes the json so it can be put on one line in the CloudFormation template.
      DockerOptions: '{{ keights_stack.etcd.docker_options | default(default_docker_options) | to_nice_json | to_json }}'
    tags:
      KubernetesCluster: '{{ keights_stack.cluster_name }}'
      k8s:version: '{{ k8s_version }}'
      keights:version: '{{ keights_version }}'
  register: etcd_stack
  tags:
    - etcd
  when: 'etcd_mode == "external"'

- name: build master stack
  cloudformation:
    stack_name: '{{ keights_stack.cluster_name }}-master'
    role_arn: '{{ keights_stack.cfn_role_arn | default(omit) }}'
    template: '{{ role_path }}/files/master-external.yml'
    template_parameters:
      ClusterName: '{{ keights_stack.cluster_name }}'
      NumInstances: '{{ keights_stack.masters.num_instances | default(1) }}'
      VpcId: '{{ keights_stack.vpc_id }}'
      MasterSubnetIds: '{{ keights_stack.masters.subnet_ids | join(",") }}'
      LoadBalancerSubnetIds: '{{ keights_stack.masters.subnet_ids | join(",") }}'
      ImageId: '{{ keights_stack.masters.image_id if keights_stack.masters.image_id is defined else image_id }}'
      InstanceType: '{{ keights_stack.masters.instance_type }}'
      KeyPair: '{{ keights_stack.masters.keypair }}'
      InstanceProfile: '{{ master_instance_profile }}'
      LoadBalancerScheme: '{{ keights_stack.masters.load_balancer_scheme }}'
      LoadBalancerSecurityGroup: '{{ common_stack.stack_outputs.LoadBalancerSecurityGroup }}'
      LoadBalancerIdleTimeout: '{{ keights_stack.masters.load_balancer_idle_timeout | default(600) }}'
      SecurityGroups: '{{ ([common_stack.stack_outputs.MasterSecurityGroup] + keights_stack.masters.extra_security_groups | default([])) | join(",") }}'
      InstanceAttributeFunctionArn: '{{ common_stack.stack_outputs.InstanceAttributeFunctionArn }}'
      PodCidr: '{{ keights_stack.masters.pod_cidr }}'
      ServiceCidr: '{{ keights_stack.masters.service_cidr }}'
      ClusterDns: '{{ cluster_dns }}'
      ClusterDomain: '{{ keights_stack.cluster_domain | default("cluster.local") }}'
      EtcdDomain: '{{ keights_stack.etcd_domain | default(default_etcd_domain) }}'
      EtcdPrefix: '{{ keights_stack.etcd_prefix | default("etcd") }}'
      EtcdAvailabilityZones: '{{ etcd_stack.stack_outputs.AvailabilityZones }}'
      ImageRepository: '{{ keights_stack.masters.image_repository | default("k8s.gcr.io") }}'
      KubernetesVersion: '{{ k8s_version }}'
      KeightsVersion: '{{ keights_version }}'
      ResourceBucket: '{{ keights_stack.resource_bucket }}'
      HostedZoneId: '{{ common_stack.stack_outputs.HostedZoneId | default(keights_stack.etcd_hosted_zone_id) }}'
      DockerOptions: '{{ keights_stack.masters.docker_options | default(default_docker_options) | to_nice_json | to_json }}'
      KubeadmInitConfigTemplate: '{{ keights_stack.masters.kubeadm_init_config_template | to_json if keights_stack.masters.kubeadm_init_config_template is defined else "" }}'
    tags:
      KubernetesCluster: '{{ keights_stack.cluster_name }}'
      k8s:version: '{{ k8s_version }}'
      keights:version: '{{ keights_version }}'
  register: master_stack_external
  tags:
    - master
  when: 'etcd_mode == "external"'

- name: build master stack
  cloudformation:
    stack_name: '{{ keights_stack.cluster_name }}-master'
    role_arn: '{{ keights_stack.cfn_role_arn | default(omit) }}'
    template: '{{ role_path }}/files/master-stacked.yml'
    template_parameters:
      ClusterName: '{{ keights_stack.cluster_name }}'
      NumInstances: '{{ keights_stack.masters.subnet_ids | length }}'
      VpcId: '{{ keights_stack.vpc_id }}'
      SubnetIds: '{{ keights_stack.masters.subnet_ids | join(",") }}'
      LoadBalancerSubnetIds: '{{ keights_stack.masters.subnet_ids | join(",") }}'
      ImageId: '{{ keights_stack.masters.image_id if keights_stack.masters.image_id is defined else image_id }}'
      InstanceType: '{{ keights_stack.masters.instance_type }}'
      KeyPair: '{{ keights_stack.masters.keypair }}'
      MasterInstanceProfile: '{{ master_instance_profile }}'
      LoadBalancerScheme: '{{ keights_stack.masters.load_balancer_scheme }}'
      LoadBalancerSecurityGroup: '{{ common_stack.stack_outputs.LoadBalancerSecurityGroup }}'
      LoadBalancerIdleTimeout: '{{ keights_stack.masters.load_balancer_idle_timeout | default(600) }}'
      MasterSecurityGroups: '{{ ([common_stack.stack_outputs.MasterSecurityGroup] + keights_stack.masters.extra_security_groups | default([])) | join(",") }}'
      AutoNamerLambdaRoleArn: '{{ auto_namer_lambda_role_arn }}'
      KubeCaLambdaRoleArn: '{{ kube_ca_lambda_role_arn }}'
      SubnetToAzLambdaRoleArn: '{{ subnet_to_az_lambda_role_arn }}'
      InstanceAttributeFunctionArn: '{{ common_stack.stack_outputs.InstanceAttributeFunctionArn }}'
      KmsKeyId: '{{ keights_stack.kms_key_alias }}'
      PodCidr: '{{ keights_stack.masters.pod_cidr }}'
      ServiceCidr: '{{ keights_stack.masters.service_cidr }}'
      ClusterDns: '{{ cluster_dns }}'
      ClusterDomain: '{{ keights_stack.cluster_domain | default("cluster.local") }}'
      EtcdDomain: '{{ keights_stack.etcd_domain | default(default_etcd_domain) }}'
      EtcdPrefix: '{{ keights_stack.etcd_prefix | default("etcd") }}'
      EtcdVolumeSize: '{{ keights_stack.masters.etcd_volume_size | default(10) }}'
      EtcdDevice: '{{ etcd_device if etcd_device.startswith("/dev/") else "/dev/{}".format(etcd_device) }}'
      ImageRepository: '{{ keights_stack.masters.image_repository | default("k8s.gcr.io") }}'
      KubernetesVersion: '{{ k8s_version }}'
      KeightsVersion: '{{ keights_version }}'
      ResourceBucket: '{{ keights_stack.resource_bucket }}'
      HostedZoneId: '{{ common_stack.stack_outputs.HostedZoneId | default(keights_stack.etcd_hosted_zone_id) }}'
      DockerOptions: '{{ keights_stack.masters.docker_options | default(default_docker_options) | to_nice_json | to_json }}'
      KubeadmInitConfigTemplate: '{{ keights_stack.masters.kubeadm_init_config_template | to_json if keights_stack.masters.kubeadm_init_config_template is defined else "" }}'
    tags:
      KubernetesCluster: '{{ keights_stack.cluster_name }}'
      k8s:version: '{{ k8s_version }}'
      keights:version: '{{ keights_version }}'
  register: master_stack_stacked
  tags:
    - master
  when: 'etcd_mode == "stacked"'

- name: set master stack
  set_fact:
    master_stack: '{{ master_stack_external if "stack_outputs" in master_stack_external else master_stack_stacked }}'

- name: build node stack
  cloudformation:
    stack_name: '{{ keights_stack.cluster_name }}-node-{{ item.name }}'
    role_arn: '{{ keights_stack.cfn_role_arn | default(omit) }}'
    template: '{{ role_path }}/files/node.yml'
    template_parameters:
      ClusterName: '{{ keights_stack.cluster_name }}'
      MinInstances: '{{ item.min_instances }}'
      MaxInstances: '{{ item.max_instances }}'
      UpdateMaxBatchSize: '{{ item.update_max_batch_size | default(1) }}'
      VpcId: '{{ keights_stack.vpc_id }}'
      SubnetIds: '{{ item.subnet_ids | join(",") }}'
      ImageId: '{{ item.image_id if item.image_id is defined else image_id }}'
      InstanceTypes: '{{ (([item.instance_type] if item.instance_type is defined else []) + item.instance_types | default([])) | unique | join(",") }}'
      KeyPair: '{{ item.keypair }}'
      NodeInstanceProfile: '{{ common_stack.stack_outputs.NodeInstanceProfile | default(item.instance_profile) }}'
      NodeSecurityGroups: '{{ ([common_stack.stack_outputs.NodeSecurityGroup] + item.extra_security_groups | default([])) | join(",") }}'
      InstanceAttributeFunctionArn: '{{ common_stack.stack_outputs.InstanceAttributeFunctionArn }}'
      ClusterDns: '{{ cluster_dns }}'
      NodeLabels: '{% set j = joiner(",") %}{% for k, v in item.node_labels.items() | default({}) %}{{ j() }}{{ k }}={{ v }}{% endfor %}'
      LoadBalancerDnsName: '{{ master_stack.stack_outputs.LoadBalancerDnsName }}'
      ImageRepository: '{{ item.image_repository | default("k8s.gcr.io") }}'
      DockerOptions: '{{ item.docker_options | default(default_docker_options) | to_nice_json | to_json }}'
      KubeadmJoinConfigTemplate: '{{ item.kubeadm_join_config_template | to_json if item.kubeadm_join_config_template is defined else "" }}'
      OnDemandPercentage: '{{ item.spot.on_demand_percentage | default(omit) }}'
      SpotAllocationStrategy: '{{ item.spot.allocation_strategy | default(omit) }}'
      SpotInstancePools: '{{ item.spot.instance_pools | default(omit) }}'
      SpotMaxPrice: '{{ item.spot.max_price | default(omit) }}'
      BasicLambdaRoleArn: '{{ basic_lambda_role_arn }}'
    tags:
      KubernetesCluster: '{{ keights_stack.cluster_name }}'
      k8s:version: '{{ k8s_version }}'
      keights:version: '{{ keights_version }}'
  loop: '{{ keights_stack.node_groups }}'
  tags:
    - nodes

- name: map node subnets to tags
  set_fact:
    subnet_tag_map: '{{ subnet_tag_map | combine(dict(item.subnet_ids | zip_longest([], fillvalue=node_groups[idx].subnet_tags) | list)) }}'
  loop: '{{ keights_stack.node_groups }}'
  loop_control:
    index_var: idx
  when: '"subnet_tags" in item'

- name: collect subnet facts
  ec2_vpc_subnet_info:
    filters:
      subnet-id: '{{ item.key }}'
  loop: '{{ subnet_tag_map | dict2items }}'
  register: node_subnet_info

- name: tag node subnets
  ec2_vpc_subnet:
    vpc_id: '{{ keights_stack.vpc_id }}'
    cidr: '{{ item.subnets.0.cidr_block }}'
    map_public: '{{ item.subnets.0.map_public_ip_on_launch }}'
    tags: '{{ item.item.value }}'
    purge_tags: false
  loop: '{{ node_subnet_info.results }}'
