#!/bin/sh -e

: ${CLUSTER:?CLUSTER must be set}

VARS=${VARS:-vars.yml}

if [ ! -f "${VARS}" ]; then
    echo "Missing vars file ${VARS}"
    exit 1
fi

searchvirt()
{
    # Nowadays prefer Python 3
    if which python3 1>/dev/null; then
       echo 'python3 -m venv'
       return
    fi
    which virtualenv
}

PYTHON_BASE="${PYTHON_BASE:-./.cache/virtualenv}"

if [ ! -d ${PYTHON_BASE} ]; then
    venv=`searchvirt`
    [ -n "${venv}" ] && ${venv} ${PYTHON_BASE}
fi

${PYTHON_BASE}/bin/pip install -r requirements.txt

[ -f requirements.yml ] && ${PYTHON_BASE}/bin/ansible-galaxy install -f -r requirements.yml

${PYTHON_BASE}/bin/ansible-playbook playbook.yml -e cluster=${CLUSTER} -e @${VARS} ${@}
