#!/bin/sh -e

: ${CLUSTER:?CLUSTER must be set}

if [ ! -f "./vars/${CLUSTER}.yml" ]; then
    echo "Missing ./vars/${CLUSTER}.yml"
    exit 1
fi

searchvirt()
{
    # Nowadays prefer Python 3
    if which python3 1>/dev/null; then
	echo 'python3 -m venv'
	return
    fi
    which virtualenv
}

PYTHON_BASE="${PYTHON_BASE:-./.virtualenv}"

if [ ! -d ${PYTHON_BASE} ]; then
    venv=`searchvirt`
    [ -n "${venv}" ] && ${venv} ${PYTHON_BASE}
fi

${PYTHON_BASE}/bin/pip install -r requirements.txt

${PYTHON_BASE}/bin/ansible-playbook playbook.yml -e cluster=${CLUSTER} ${@}
