- hosts: localhost
  connection: local

  vars_files:
    - vars/{{ cluster }}.yml

  vars:
    cf_base: ../cloudformation

  tasks:
    - name: set cluster dns ip from service cidr
      set_fact:
        cluster_dns: '{{ service_cidr.split(".")[:-1] | join(".") }}.10'

    - name: build common stack
      cloudformation:
        stack_name: '{{ cluster_name }}-common'
        template: '{{ cf_base }}/common.yml'
        template_parameters:
          VpcId: '{{ vpc_id }}'
          ClusterName: '{{ cluster_name }}'
          KmsKeyId: '{{ kms_key_id }}'
          ApiAccessCidr: '{{ api_access_cidr }}'
          SshAccessCidr: '{{ ssh_access_cidr }}'
        tags:
          KubernetesCluster: '{{ cluster_name }}'
      register: common_stack
      tags:
        - common

    - name: build master stack
      cloudformation:
        stack_name: '{{ cluster_name }}-master'
        template: '{{ cf_base }}/master.yml'
        template_parameters:
          ClusterName: '{{ cluster_name }}'
          NumInstances: '{{ num_masters }}'
          VpcId: '{{ vpc_id }}'
          SubnetIds: '{{ subnet_ids }}'
          LoadBalancerSubnetIds: '{{ subnet_ids }}'
          ImageId: '{{ image_id }}'
          InstanceType: '{{ master_instance_type }}'
          KeyPair: '{{ keypair }}'
          MasterInstanceProfile: '{{ common_stack.stack_outputs.MasterInstanceProfile }}'
          LoadBalancerScheme: '{{ load_balancer_scheme }}'
          LoadBalancerSecurityGroup: '{{ common_stack.stack_outputs.LoadBalancerSecurityGroup }}'
          MasterSecurityGroups: '{{ ([common_stack.stack_outputs.MasterSecurityGroup] + extra_master_security_groups | default([])) | join(",") }}'
          LambdaRoleArn: '{{ common_stack.stack_outputs.LambdaRoleArn }}'
          KmsKeyId: '{{ kms_key_alias }}'
          PodCidr: '{{ pod_cidr }}'
          ServiceCidr: '{{ service_cidr }}'
          ClusterDns: '{{ cluster_dns }}'
          EtcdVolumeSize: '{{ etcd_volume_size }}'
          ImageRepository: 'k8s.gcr.io'
          EtcdImage: '{{ etcd_image }}'
          KubernetesVersion: '{{ k8s_version }}'
          ResourceBucket: '{{ resource_bucket }}'
        tags:
          KubernetesCluster: '{{ cluster_name }}'
      register: master_stack
      tags:
        - master

    - name: build node stack
      cloudformation:
        stack_name: '{{ cluster_name }}-node-{{ item.name }}'
        template: '{{ cf_base }}/node.yml'
        template_parameters:
          ClusterName: '{{ cluster_name }}'
          NumInstances: '{{ item.num_nodes }}'
          VpcId: '{{ item.vpc_id }}'
          SubnetIds: '{{ item.subnet_ids }}'
          ImageId: '{{ item.image_id }}'
          InstanceType: '{{ item.instance_type }}'
          KeyPair: '{{ item.keypair }}'
          NodeInstanceProfile: '{{ common_stack.stack_outputs.NodeInstanceProfile }}'
          NodeSecurityGroups: '{{ ([common_stack.stack_outputs.NodeSecurityGroup] + item.extra_security_groups | default([])) | join(",") }}'
          ClusterDns: '{{ cluster_dns }}'
          NodeLabels: '{{ item.node_labels | default("") }}'
          LoadBalancerDnsName: '{{ master_stack.stack_outputs.LoadBalancerDnsName }}'
        tags:
          KubernetesCluster: '{{ cluster_name }}'
      with_items: '{{ node_groups }}'
      tags:
        - nodes
