// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Whisperer is an autogenerated mock type for the Whisperer type
type Whisperer struct {
	mock.Mock
}

// DeleteParameter provides a mock function with given fields: path
func (_m *Whisperer) DeleteParameter(path *string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(*string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForceStoreParameter provides a mock function with given fields: path, kmsKeyID, content
func (_m *Whisperer) ForceStoreParameter(path string, kmsKeyID string, content *string) error {
	ret := _m.Called(path, kmsKeyID, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *string) error); ok {
		r0 = rf(path, kmsKeyID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreParameter provides a mock function with given fields: path, kmsKeyID, content
func (_m *Whisperer) StoreParameter(path string, kmsKeyID string, content *string) error {
	ret := _m.Called(path, kmsKeyID, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *string) error); ok {
		r0 = rf(path, kmsKeyID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
