# This file sets common variables for a Kubernetes cluster. The stack
# defined in this directory is designed to work using default values.
# More fine grained control is possible by editing playbook.yml and
# modifying it using the options documented in the role's README.
#
# The AWS identifiers in this file are not real and must be replaced
# with your own.

# ID of VPC.
vpc_id: vpc-ba92ad08

# For masters, each subnet must be in a different availability zone.
# The number of subnets determines the number of masters. Either one
# or three subnets may be used for the masters.
master_subnet_ids:
  - subnet-6c31888d

# Nodes do not have any restrictions on the subnets that may be used,
# except that they must be in the same VPC as the masters.
node_subnet_ids:
  - subnet-6c31888d
  - subnet-f3cdd152
  - subnet-e245724f

# Minimum and maximum number of nodes in the autoscaling group.
node_min_instances: 1
node_max_instances: 1

# KMS key ID used by SSM Parameter Store to encrypt certificates.
kms_key_id: d4baff42-9ea6-4f7d-a866-136587c77815

# Alias of the KMS key ID above. Using an alias makes it easier to see
# which KMS key encrypted the certificates, when viewing SSM Parameters
# in the AWS console.
kms_key_alias: alias/cloudboss

# SSH keypair to assign to instances.
keypair: keights
